### ISSUE TITLE
dist/commonjs/index.js not found

### ISSUE THREAD

**Issue by kenixer** [davidbkemp/jsqubits#23]
Looks like jsqubits runner has stable architecture, but this repo doesn't.
It says 
`Failed to load resource: the server responded with a status of 404 (File not found)`.
So I can be sure there must be some directory like `dist`, but there isn't(at least in this github repo). Perhaps there are some differences between runner's version and repo.

Basically, I need some help of this library's author...to make some working quantum program.

**Comment by omphalos** [comment]
Take a look at package.json, dist files appear to get built with build commands.

**Comment by omphalos** [comment]
> Looks like jsqubits runner has stable architecture, but this repo doesn't

By the way, it's common practice to omit build artifacts from a repo :)

**Comment by davidbkemp** [comment]
I am sorry to hear you are having problems with this.  A little bit more information would help me, so that I can update the documentation to make it easier for the next person.

What method did you use to download the library?  Did you `git clone` the repository, or did you download a zip of the current master, or download one of the releases?

Having downloaded it, did you run `npm install` ?

**Comment by kenixer** [comment]
No...I didn't tried npm install. Sorry about missing that, since I'm quite newbie to JS. 
Anyway, thanks. I will try that.
